name: Step 1, Basic Completion

# This step triggers after basic completion tasks
on:
  workflow_dispatch:
  push:
    paths:
      - "src/**/*.js"
      - "src/**/*.ts"
      - "src/**/*.tsx"
    branches:
      - main

permissions:
  contents: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_basic_completion:
    name: On Basic Completion
    needs: get_current_step
    if: ${{ !github.event.repository.is_template && needs.get_current_step.outputs.current_step == 1 }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check file changes
        uses: skills/action-check-file@v1
        with:
          file: "src/**/*.{js,ts,tsx}"
          search: "function"

      - name: Update to step 2
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 1
          to_step: 2
